services:
  - type: web
    name: magazyn-ocr
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libgl1-mesa-glx && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
