services:
  - type: web
    name: magazyn-ocr
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    preInstallCommand: |
      apt-get update && \
      apt-get install -y libgl1
